# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
 # lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
    lane :BuildApp do
exportmethod = UI.input("Enter Export Method..(enterprise/development)")
scheme = UI.input("Enter scheme name")
isWorkSpace = false
if UI.confirm(“Do you have pods installed?”)
build_ios_app(
workspace: "#{scheme}.xcworkspace",
scheme: scheme,
silent: true,
clean: true,
export_method: exportmethod,
output_directory: "./Build”,
output_name: "#{scheme}.ipa"
)
diawi(
token: "Tw3SrpEIo7Oy48sjBZA4B7fyrQC1Yyfbzpo1lgMbfb",
file: "./Build/#{scheme}.ipa",
callback_emails: "aqassessor@gmail.com"
)
else
build_ios_app(
scheme: scheme,
silent: true,
clean: true,
export_method: exportmethod,
output_directory: "./Build",
output_name: "#{scheme}.ipa"
)
diawi(
token: "Tw3SrpEIo7Oy48sjBZA4B7fyrQC1Yyfbzpo1lgMbfb",
file: "./Build/#{scheme}.ipa",
callback_emails: "aqassessor@gmail.com"
)
end
end
end
#end
